name = "vault-picks"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "VAULT_BUCKET"
bucket_name = "salus-mind"

[vars]
AUTH_TOKEN = "salus-vault-2026"

[[routes]]
pattern = "vault-picks.salus-mind.com"
custom_domain = true
